name: React app deployement

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Deploy react app to github pages
      env:
        REACT_APP_API_KEY: ${{secrets.REACT_APP_API_KEY}}
        REACT_APP_AUTH_DOMAIN: ${{secrets.REACT_APP_AUTH_DOMAIN}}
        REACT_APP_PROJECT_ID: ${{secrets.REACT_APP_PROJECT_ID}}
        REACT_APP_STORAGE_BUCKET: ${{secrets.REACT_APP_STORAGE_BUCKET}}
        REACT_APP_MESSAGING_SENDER_ID: ${{secrets.REACT_APP_MESSAGING_SENDER_ID}}
        REACT_APP_APP_ID: ${{secrets.REACT_APP_APP_ID}}
        REACT_APP_MEASUREMENT_ID: ${{secrets.REACT_APP_MEASUREMENT_ID}}
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1